/*
 * This file is generated by jOOQ.
 */
package sec.hdlt.server.db.database.tables.pojos;


import java.io.Serializable;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BroadcastNonces implements Serializable {

    private static final long serialVersionUID = 1L;

    private final UInteger serverId;
    private final byte[]   nonce;

    public BroadcastNonces(BroadcastNonces value) {
        this.serverId = value.serverId;
        this.nonce = value.nonce;
    }

    public BroadcastNonces(
        UInteger serverId,
        byte[]   nonce
    ) {
        this.serverId = serverId;
        this.nonce = nonce;
    }

    /**
     * Getter for <code>broadcast_nonces.server_id</code>.
     */
    public UInteger getServerId() {
        return this.serverId;
    }

    /**
     * Getter for <code>broadcast_nonces.nonce</code>.
     */
    public byte[] getNonce() {
        return this.nonce;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BroadcastNonces (");

        sb.append(serverId);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
