/*
 * This file is generated by jOOQ.
 */
package sec.hdlt.server.db.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HaNonces implements Serializable {

    private static final long serialVersionUID = 1L;

    private final byte[] nonce;

    public HaNonces(HaNonces value) {
        this.nonce = value.nonce;
    }

    public HaNonces(
        byte[] nonce
    ) {
        this.nonce = nonce;
    }

    /**
     * Getter for <code>ha_nonces.nonce</code>.
     */
    public byte[] getNonce() {
        return this.nonce;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HaNonces (");

        sb.append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
