/*
 * This file is generated by jOOQ.
 */
package sec.hdlt.server.db.database.tables.pojos;


import java.io.Serializable;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Proofs implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer  id;
    private final UInteger otherUserId;
    private final UInteger reportId;
    private final String   signature;

    public Proofs(Proofs value) {
        this.id = value.id;
        this.otherUserId = value.otherUserId;
        this.reportId = value.reportId;
        this.signature = value.signature;
    }

    public Proofs(
        Integer  id,
        UInteger otherUserId,
        UInteger reportId,
        String   signature
    ) {
        this.id = id;
        this.otherUserId = otherUserId;
        this.reportId = reportId;
        this.signature = signature;
    }

    /**
     * Getter for <code>proofs.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>proofs.other_user_id</code>.
     */
    public UInteger getOtherUserId() {
        return this.otherUserId;
    }

    /**
     * Getter for <code>proofs.report_id</code>.
     */
    public UInteger getReportId() {
        return this.reportId;
    }

    /**
     * Getter for <code>proofs.signature</code>.
     */
    public String getSignature() {
        return this.signature;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Proofs (");

        sb.append(id);
        sb.append(", ").append(otherUserId);
        sb.append(", ").append(reportId);
        sb.append(", ").append(signature);

        sb.append(")");
        return sb.toString();
    }
}
