/*
 * This file is generated by jOOQ.
 */
package sec.hdlt.server.db.database;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import sec.hdlt.server.db.database.tables.BroadcastNonces;
import sec.hdlt.server.db.database.tables.HaNonces;
import sec.hdlt.server.db.database.tables.Nonces;
import sec.hdlt.server.db.database.tables.Proofs;
import sec.hdlt.server.db.database.tables.Reports;
import sec.hdlt.server.db.database.tables.SqliteSequence;
import sec.hdlt.server.db.database.tables.UserRequests;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>broadcast_nonces</code>.
     */
    public final BroadcastNonces BROADCAST_NONCES = BroadcastNonces.BROADCAST_NONCES;

    /**
     * The table <code>ha_nonces</code>.
     */
    public final HaNonces HA_NONCES = HaNonces.HA_NONCES;

    /**
     * The table <code>nonces</code>.
     */
    public final Nonces NONCES = Nonces.NONCES;

    /**
     * The table <code>proofs</code>.
     */
    public final Proofs PROOFS = Proofs.PROOFS;

    /**
     * The table <code>reports</code>.
     */
    public final Reports REPORTS = Reports.REPORTS;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>user_requests</code>.
     */
    public final UserRequests USER_REQUESTS = UserRequests.USER_REQUESTS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            BroadcastNonces.BROADCAST_NONCES,
            HaNonces.HA_NONCES,
            Nonces.NONCES,
            Proofs.PROOFS,
            Reports.REPORTS,
            SqliteSequence.SQLITE_SEQUENCE,
            UserRequests.USER_REQUESTS);
    }
}
