/*
 * This file is generated by jOOQ.
 */
package sec.hdlt.server.db.database;


import sec.hdlt.server.db.database.tables.Proofs;
import sec.hdlt.server.db.database.tables.Reports;
import sec.hdlt.server.db.database.tables.SqliteSequence;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>proofs</code>.
     */
    public static final Proofs PROOFS = Proofs.PROOFS;

    /**
     * The table <code>reports</code>.
     */
    public static final Reports REPORTS = Reports.REPORTS;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;
}
