/*
 * This file is generated by jOOQ.
 */
package sec.hdlt.server.db;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import sec.hdlt.server.db.tables.Proofs;
import sec.hdlt.server.db.tables.Reports;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>proofs</code>.
     */
    public final Proofs PROOFS = Proofs.PROOFS;

    /**
     * The table <code>reports</code>.
     */
    public final Reports REPORTS = Reports.REPORTS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Proofs.PROOFS,
            Reports.REPORTS);
    }
}
