/*
 * This file is generated by jOOQ.
 */
package sec.hdlt.server.db;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import sec.hdlt.server.db.tables.Proofs;
import sec.hdlt.server.db.tables.Reports;
import sec.hdlt.server.db.tables.records.ProofsRecord;
import sec.hdlt.server.db.tables.records.ReportsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ProofsRecord> PK_PROOFS = Internal.createUniqueKey(Proofs.PROOFS, DSL.name("pk_proofs"), new TableField[] { Proofs.PROOFS.ID }, true);
    public static final UniqueKey<ReportsRecord> PK_REPORTS = Internal.createUniqueKey(Reports.REPORTS, DSL.name("pk_reports"), new TableField[] { Reports.REPORTS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ProofsRecord, ReportsRecord> FK_PROOFS_REPORTS_1 = Internal.createForeignKey(Proofs.PROOFS, DSL.name("fk_proofs_reports_1"), new TableField[] { Proofs.PROOFS.REPORT_ID }, Keys.PK_REPORTS, new TableField[] { Reports.REPORTS.ID }, true);
}
