/*
 * This file is generated by jOOQ.
 */
package sec.hdlt.server.db;


import sec.hdlt.server.db.tables.Proofs;
import sec.hdlt.server.db.tables.Reports;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>proofs</code>.
     */
    public static final Proofs PROOFS = Proofs.PROOFS;

    /**
     * The table <code>reports</code>.
     */
    public static final Reports REPORTS = Reports.REPORTS;
}
