/*
 * This file is generated by jOOQ.
 */
package sec.hdlt.server.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Proofs implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Object id;
    private final Object otherUserId;
    private final Object reportId;
    private final String signature;

    public Proofs(Proofs value) {
        this.id = value.id;
        this.otherUserId = value.otherUserId;
        this.reportId = value.reportId;
        this.signature = value.signature;
    }

    public Proofs(
        Object id,
        Object otherUserId,
        Object reportId,
        String signature
    ) {
        this.id = id;
        this.otherUserId = otherUserId;
        this.reportId = reportId;
        this.signature = signature;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getId() {
        return this.id;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getOtherUserId() {
        return this.otherUserId;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getReportId() {
        return this.reportId;
    }

    /**
     * Getter for <code>proofs.signature</code>.
     */
    public String getSignature() {
        return this.signature;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Proofs (");

        sb.append(id);
        sb.append(", ").append(otherUserId);
        sb.append(", ").append(reportId);
        sb.append(", ").append(signature);

        sb.append(")");
        return sb.toString();
    }
}
