/*
 * This file is generated by jOOQ.
 */
package sec.hdlt.server.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reports implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Object id;
    private final Object epoch;
    private final Object userId;
    private final Object x;
    private final Object y;

    public Reports(Reports value) {
        this.id = value.id;
        this.epoch = value.epoch;
        this.userId = value.userId;
        this.x = value.x;
        this.y = value.y;
    }

    public Reports(
        Object id,
        Object epoch,
        Object userId,
        Object x,
        Object y
    ) {
        this.id = id;
        this.epoch = epoch;
        this.userId = userId;
        this.x = x;
        this.y = y;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getId() {
        return this.id;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getEpoch() {
        return this.epoch;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getUserId() {
        return this.userId;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getX() {
        return this.x;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getY() {
        return this.y;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Reports (");

        sb.append(id);
        sb.append(", ").append(epoch);
        sb.append(", ").append(userId);
        sb.append(", ").append(x);
        sb.append(", ").append(y);

        sb.append(")");
        return sb.toString();
    }
}
