/*
 * This file is generated by jOOQ.
 */
package sec.hdlt.server.db.database.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;

import sec.hdlt.server.db.database.DefaultSchema;
import sec.hdlt.server.db.database.Keys;
import sec.hdlt.server.db.database.tables.records.NoncesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Nonces extends TableImpl<NoncesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>nonces</code>
     */
    public static final Nonces NONCES = new Nonces();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NoncesRecord> getRecordType() {
        return NoncesRecord.class;
    }

    /**
     * The column <code>nonces.user_id</code>.
     */
    public final TableField<NoncesRecord, UInteger> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>nonces.nonce</code>.
     */
    public final TableField<NoncesRecord, byte[]> NONCE = createField(DSL.name("nonce"), SQLDataType.VARBINARY.nullable(false), this, "");

    private Nonces(Name alias, Table<NoncesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Nonces(Name alias, Table<NoncesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>nonces</code> table reference
     */
    public Nonces(String alias) {
        this(DSL.name(alias), NONCES);
    }

    /**
     * Create an aliased <code>nonces</code> table reference
     */
    public Nonces(Name alias) {
        this(alias, NONCES);
    }

    /**
     * Create a <code>nonces</code> table reference
     */
    public Nonces() {
        this(DSL.name("nonces"), null);
    }

    public <O extends Record> Nonces(Table<O> child, ForeignKey<O, NoncesRecord> key) {
        super(child, key, NONCES);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<NoncesRecord> getPrimaryKey() {
        return Keys.PK_NONCES;
    }

    @Override
    public List<UniqueKey<NoncesRecord>> getKeys() {
        return Arrays.<UniqueKey<NoncesRecord>>asList(Keys.PK_NONCES);
    }

    @Override
    public Nonces as(String alias) {
        return new Nonces(DSL.name(alias), this);
    }

    @Override
    public Nonces as(Name alias) {
        return new Nonces(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Nonces rename(String name) {
        return new Nonces(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Nonces rename(Name name) {
        return new Nonces(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UInteger, byte[]> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
