/*
 * This file is generated by jOOQ.
 */
package sec.hdlt.server.db.database.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;

import sec.hdlt.server.db.database.DefaultSchema;
import sec.hdlt.server.db.database.Keys;
import sec.hdlt.server.db.database.tables.records.ReportsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reports extends TableImpl<ReportsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reports</code>
     */
    public static final Reports REPORTS = new Reports();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReportsRecord> getRecordType() {
        return ReportsRecord.class;
    }

    /**
     * The column <code>reports.id</code>.
     */
    public final TableField<ReportsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>reports.epoch</code>.
     */
    public final TableField<ReportsRecord, UInteger> EPOCH = createField(DSL.name("epoch"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>reports.user_id</code>.
     */
    public final TableField<ReportsRecord, UInteger> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>reports.x</code>.
     */
    public final TableField<ReportsRecord, UInteger> X = createField(DSL.name("x"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>reports.y</code>.
     */
    public final TableField<ReportsRecord, UInteger> Y = createField(DSL.name("y"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    private Reports(Name alias, Table<ReportsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Reports(Name alias, Table<ReportsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>reports</code> table reference
     */
    public Reports(String alias) {
        this(DSL.name(alias), REPORTS);
    }

    /**
     * Create an aliased <code>reports</code> table reference
     */
    public Reports(Name alias) {
        this(alias, REPORTS);
    }

    /**
     * Create a <code>reports</code> table reference
     */
    public Reports() {
        this(DSL.name("reports"), null);
    }

    public <O extends Record> Reports(Table<O> child, ForeignKey<O, ReportsRecord> key) {
        super(child, key, REPORTS);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<ReportsRecord, Integer> getIdentity() {
        return (Identity<ReportsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReportsRecord> getPrimaryKey() {
        return Keys.PK_REPORTS;
    }

    @Override
    public List<UniqueKey<ReportsRecord>> getKeys() {
        return Arrays.<UniqueKey<ReportsRecord>>asList(Keys.PK_REPORTS);
    }

    @Override
    public Reports as(String alias) {
        return new Reports(DSL.name(alias), this);
    }

    @Override
    public Reports as(Name alias) {
        return new Reports(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Reports rename(String name) {
        return new Reports(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Reports rename(Name name) {
        return new Reports(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, UInteger, UInteger, UInteger, UInteger> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
