/*
 * This file is generated by jOOQ.
 */
package sec.hdlt.server.db.database.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;

import sec.hdlt.server.db.database.DefaultSchema;
import sec.hdlt.server.db.database.Keys;
import sec.hdlt.server.db.database.tables.records.UserRequestsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRequests extends TableImpl<UserRequestsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>user_requests</code>
     */
    public static final UserRequests USER_REQUESTS = new UserRequests();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserRequestsRecord> getRecordType() {
        return UserRequestsRecord.class;
    }

    /**
     * The column <code>user_requests.user_id</code>.
     */
    public final TableField<UserRequestsRecord, UInteger> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>user_requests.timestamp</code>.
     */
    public final TableField<UserRequestsRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    private UserRequests(Name alias, Table<UserRequestsRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserRequests(Name alias, Table<UserRequestsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>user_requests</code> table reference
     */
    public UserRequests(String alias) {
        this(DSL.name(alias), USER_REQUESTS);
    }

    /**
     * Create an aliased <code>user_requests</code> table reference
     */
    public UserRequests(Name alias) {
        this(alias, USER_REQUESTS);
    }

    /**
     * Create a <code>user_requests</code> table reference
     */
    public UserRequests() {
        this(DSL.name("user_requests"), null);
    }

    public <O extends Record> UserRequests(Table<O> child, ForeignKey<O, UserRequestsRecord> key) {
        super(child, key, USER_REQUESTS);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<UserRequestsRecord> getPrimaryKey() {
        return Keys.PK_USER_REQUESTS;
    }

    @Override
    public List<UniqueKey<UserRequestsRecord>> getKeys() {
        return Arrays.<UniqueKey<UserRequestsRecord>>asList(Keys.PK_USER_REQUESTS);
    }

    @Override
    public UserRequests as(String alias) {
        return new UserRequests(DSL.name(alias), this);
    }

    @Override
    public UserRequests as(Name alias) {
        return new UserRequests(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserRequests rename(String name) {
        return new UserRequests(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserRequests rename(Name name) {
        return new UserRequests(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UInteger, LocalDateTime> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
